.TH TREESHOT 1 "October 2021" "MIT License" "User Commands"
.SH NAME
.PP
treeshot - L3af\[aq]s mediocre screenshot tool
.SH SYNOPSIS
.PP
\f[B]treeshot\f[R] [\f[I]OPTIONS\f[R]]
Capture a screenshot and copy to clipboard, to save to a file redirect stdout to the desired location.
.SH DESCRIPTION
.PP
\f[B]treeshot\f[R] is a tool to screenshot your screen and add a colored
border.
.SH EXAMPLES
.TP
\f[B]treeshot -s -w\f[R]\f[I]10\f[R] -c\f[R]\f[I]#FF0000\f[R]
Screenshot a region and copy to clipboard with a border of 10 pixels colored red.
.TP
\f[B]treeshot -sb\f[R]
Screenshot a region and copy to clipboard without adding a border.
.TP
\f[B]treeshot -s > \f[R]\f[I]selection.png\f[R]
Screenshot a region and save to selection.png
.TP
\f[B]treeshot -s -e"echo $file"\f[R]
Screenshot a region and copy to clipboard without adding a border.
.TP
\f[B]treeshot -s > \f[R]\f[I]selection.png\f[R]
Screenshot a region and save to selection.png
.SH OPTIONS
.PP
\f[B]-h\f[R]
.PD 0
.P
.PD
Show the help menu
.PP
\f[B]-s\f[R]
.PD 0
.P
.PD
Select region to screenshot (fullscreen by default)
.PP
\f[B]-b\f[R]
.PD 0
.P
.PD
Disable border (enabled by default
.PP
\f[B]-c\f[R]\f[I]\f[BI]#RGB\f[I]\f[R]
.PD 0
.P
.PD
Border color (#EDD7BD by default)
.PP
\f[B]-w\f[R]\f[I]\f[BI]INT\f[I]\f[R]
.PD 0
.P
.PD
Border width (4 by default)
.PP
\f[B]-d\f[R]\f[I]\f[BI]MS\f[I]\f[R]
.PD 0
.P
.PD
Capture delay in ms
.PP
\f[B]-e\f[R]\f[I]\f[BI]STRING\f[I]\f[R]
.PD 0
.P
.PD
Execute shell after capturing (Use $file to access the file)
