#!/bin/sh

selection=0
addBorder=1
borderWidth=4
borderColor="#EDD7BD"

showHelp() {
    echo "  Treeshot - L3af's Mediocre Screenshot Wrapper"
    echo " "
    echo " Examples"
    echo "   treeshot -s -w10 -b#FF0000"
    echo "     Screenshot a region and copy to clipboard with a border of 10 pixels colored red."
    echo " "
    echo "   treeshot -sd"
    echo "     Screenshot a region and copy to clipboard without adding a border."
    echo " "
    echo "   treeshot -s > selection.png"
    echo "     Screenshot a region and save to selection.png"
    echo " "
    echo " Args"
    echo "   -h  Show this help menu"
    echo "   -s  Select region to screenshot (fullscreen by default)"
    echo "   -d  Disable border (enabled by default)"
    echo "   -b  Border color (#EDD7BD by default)"
    echo "   -w  Border width (4 by default)"
    echo " "
}

while getopts ":schdb:w:" arg; do
    case $arg in
        s) selection=1;;
        d) addBorder=0;;
        b) borderColor="${OPTARG}";;
        w) borderWidth="${OPTARG}";;
        h) showHelp; exit;;
    esac
done

if [ $selection -eq 0 ]
then
    # Screenshot full screen
    import -window root /tmp/.treeshot.png
else
    # Select region
    slop=$(slop -f "%g") || exit 1
    read -r area < <(echo $slop)

    # Screenshot and crop to specified region
    import -window root -crop $area /tmp/.treeshot.png
fi

if [ $addBorder -eq 1 ]; then
    # Add border and shadow
    convert /tmp/.treeshot.png -bordercolor $borderColor -border $borderWidth /tmp/.treeshot.png
fi

if [ -t ]
then
    # Copy to clipboard
    xclip -selection clipboard -t image/png /tmp/.treeshot.png
else
    # Save to file
    OUTFILE=$(readlink /proc/$$/fd/1)
    cp /tmp/.treeshot.png
fi


# Remove file
rm /tmp/.treeshot.png

# # One liner
# maim -su | convert - -bordercolor '#EDD7BD' -border 4 /tmp/.treeshot.png; xclip -selection clipboard -t image/png /tmp/.treeshot.png; rm /tmp/.treeshot.png
